"""empty message

Revision ID: 1d7f14038dfc
Revises: e1e2bc8e820d
Create Date: 2021-04-08 02:48:59.882594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d7f14038dfc'
down_revision = 'e1e2bc8e820d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('category', sa.String(length=30), nullable=True))
    op.drop_column('character', 'type')
    op.add_column('planet', sa.Column('category', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'category')
    op.add_column('character', sa.Column('type', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('character', 'category')
    # ### end Alembic commands ###
