"""empty message

Revision ID: 802b65d75c19
Revises: 762402052503
Create Date: 2021-04-07 22:46:12.885057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802b65d75c19'
down_revision = '762402052503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###
