"""empty message

Revision ID: b9c5cb8448df
Revises: 3b96b3cc30f0
Create Date: 2021-04-07 23:40:29.890639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c5cb8448df'
down_revision = '3b96b3cc30f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('birth_year', sa.String(length=30), nullable=True))
    op.add_column('character', sa.Column('eye_color', sa.String(length=30), nullable=True))
    op.add_column('character', sa.Column('gender', sa.String(length=30), nullable=True))
    op.add_column('character', sa.Column('hair_color', sa.String(length=30), nullable=True))
    op.add_column('character', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('character', sa.Column('mass', sa.Integer(), nullable=True))
    op.add_column('character', sa.Column('skin_color', sa.String(length=30), nullable=True))
    op.add_column('planet', sa.Column('climate', sa.String(length=30), nullable=True))
    op.add_column('planet', sa.Column('diameter', sa.Integer(), nullable=True))
    op.add_column('planet', sa.Column('gravity', sa.String(length=30), nullable=True))
    op.add_column('planet', sa.Column('population', sa.Integer(), nullable=True))
    op.add_column('planet', sa.Column('surface_water', sa.Integer(), nullable=True))
    op.add_column('planet', sa.Column('terrain', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'terrain')
    op.drop_column('planet', 'surface_water')
    op.drop_column('planet', 'population')
    op.drop_column('planet', 'gravity')
    op.drop_column('planet', 'diameter')
    op.drop_column('planet', 'climate')
    op.drop_column('character', 'skin_color')
    op.drop_column('character', 'mass')
    op.drop_column('character', 'height')
    op.drop_column('character', 'hair_color')
    op.drop_column('character', 'gender')
    op.drop_column('character', 'eye_color')
    op.drop_column('character', 'birth_year')
    # ### end Alembic commands ###
