"""empty message

Revision ID: e1e2bc8e820d
Revises: b9c5cb8448df
Create Date: 2021-04-08 02:37:36.259964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e2bc8e820d'
down_revision = 'b9c5cb8448df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('type', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'type')
    # ### end Alembic commands ###
