"""empty message

Revision ID: f25a5ab273f8
Revises: 1196b64eab2c
Create Date: 2021-04-09 20:06:56.845663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25a5ab273f8'
down_revision = '1196b64eab2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='favorite')
    op.add_column('user', sa.Column('username', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    op.create_index('name', 'favorite', ['name'], unique=True)
    # ### end Alembic commands ###
